services:
  - postgresql
addons:
  postgresql: "9.6"
language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database SHOP_WITH_US;' -U postgres
  - npm install
script:
  - npm test
after_success:
  - npm run coverage