const testUser = [
  {
    name: 'test user',
    email: 'kigalicoding@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'Test user',
    email: 'testuser@test',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    verifyCode: '12345',
  },
  {
    verifyCode: '123456',
  },
  {
    email: 'dammyuser@ako.com',
    password: 'Colvert1!',
  },
  {
    email: 'fakeuser@gmail.com',
    password: 'password',
  },
  {
    email: 'fakeuser@gmail.com',
  },
  {
    name: 'Test user',
    email: 'testuser@test.com',
    phoneNumber: '0786427476',
    password: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'Test user',
    email: 'testuser@test.com',
    phoneNumber: '+250786427476',
    password: 'Testuser78',
    isBuyer: 'yes',
  },
  {
    name: 'Test user',
    email: 'testuser@test.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    email: process.env.GMAILACCOUNT,
  },
  {
    email: 'helloworld@gmail.com',
  },
  {
    email: 'helloworldgmail.com',
  },
  {
    password: 'Hello@123',
    confirmPassword: 'Hello@123',
  },
  {
    password: 'Hello',
    confirmPassword: 'Hello@123',
  },
  {
    password: 'Hello@123',
    confirmPassword: 'Hello',
  },
  {
    name: 'test user',
    email: 'kigalicoding1@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'test user',
    email: 'kigalicoding2@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'test user',
    email: 'kigalicoding3@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'test user',
    email: 'kigalicoding4@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'test user',
    email: 'kigalicoding5@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'test user',
    email: 'kigalicoding6@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'test user',
    email: 'kigalicoding7@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'test user',
    email: 'kigalicoding8@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
  {
    name: 'test user',
    email: 'kigalicoding9@gmail.com',
    phoneNumber: '+250786427476',
    password: 'Testuser@78',
    confirmPassword: 'Testuser@78',
    isBuyer: 'yes',
  },
];
export default testUser;
